[project]
name = "airplanes"
version = "0.1.0"
description = "Project for tracking airplanes"
requires-python = ">=3.12"
dependencies = [
    "requests==2.33.1",
]

[project.optional-dependencies]
dev = [
    "pytest==9.0.3",
    "pytest-cov>=4.0.0",
    "flake8==7.3.0",
    "black==26.3.1",
    "isort==8.0.1",
    "mypy==1.20.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 119
exclude = '''
/(
    \.git
    \.venv
    __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
warn_return_any = true
exclude = "venv"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"